#all
GET  https://canvas.instructure.com/doc/api/api-docs.json HTTP/1.1


GET https://canvas.instructure.com/doc/api/api_token_scopes.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/account_domain_lookups.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/account_notifications.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/account_reports.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/accounts.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/accounts_(lti).json HTTP/1.1
GET https://canvas.instructure.com/doc/api/admins.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/analytics.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/announcement_external_feeds.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/announcements.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/appointment_groups.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/assignment_extensions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/assignment_groups.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/assignments.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/authentication_providers.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/authentications_log.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/blueprint_courses.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/bookmarks.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/brand_configs.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/calendar_events.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/collaborations.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/comm_messages.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/communication_channels.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/conferences.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/content_exports.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/content_migrations.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/content_security_policy_settings.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/content_shares.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/conversations.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/course_audit_log.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/course_quiz_extensions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/courses.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/custom_gradebook_columns.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/discussion_topics.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/document_previews.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/enrollment_terms.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/enrollments.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/error_reports.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/external_tools.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/favorites.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/feature_flags.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/files.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/grade_change_log.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/gradebook_history.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/grading_periods.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/grading_standards.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/group_categories.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/groups.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/history.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/image_search.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/immersive_reader.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/jw_ts.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/late_policy.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/line_items.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/live_assessments.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/logins.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/media_objects.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/moderated_grading.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/modules.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/names_and_role.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/notification_preferences.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/originality_reports.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/outcome_groups.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/outcome_imports.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/outcome_results.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/outcomes.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/pages.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/peer_reviews.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/plagiarism_detection_platform_assignments.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/plagiarism_detection_platform_users.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/plagiarism_detection_submissions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/planner.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/poll_sessions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/poll_choices.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/poll_submissions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/polls.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/proficiency_ratings.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/progress.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/public_jwk.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_assignment_overrides.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_extensions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_ip_filters.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_question_groups.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_questions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_reports.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_statistics.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_submission_events.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_submission_files.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_submission_questions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_submission_user_list.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quiz_submissions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/quizzes.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/result.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/roles.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/rubrics.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/sis_import_errors.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/sis_imports.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/sis_integration.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/score.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/search.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/sections.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/services.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/shared_brand_configs.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/submission_comments.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/submissions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/tabs.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/user_observees.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/users.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/webhooks_subscriptions.json HTTP/1.1
GET https://canvas.instructure.com/doc/api/e_pub_exports.json HTTP/1.1
